### ISSUE TITLE
How to visualize the results？

### ISSUE THREAD

**Issue by yoyowowgogo** [ptrvilya/object-popup#2]
Hi,
I want to visualize the result as you show in the petrov23popup.gif. Could you release the code for visualizing the results? 
Thanks!

**Comment by ptrvilya** [comment]
Hey, I use [blendify](https://github.com/ptrvilya/blendify) for the visualizations in the paper, so please check it out :) The gif that you mentioned was generated by rendering with a camera moving in circle around the results. You can use [this](https://github.com/ptrvilya/blendify/blob/main/blendify/utils/camera_trajectory.py) class to obtain camera trajectory from a couple of reference points. After rendering the videos were merged using video editing software.
